area/main-binary:
  - 'main.go'
  - 'internal/**/*'
area/sdk:
  - any:
    - 'pkg/**/*'
    - '!pkg/plugin/**/*'
area/plugin:
  - 'pkg/plugin/**/*'
area/infra:
  - '.github/**/*'
  - 'Makefile'
  - '.goreleaser.yml'
  - '.golangci.yml'
area/deps:
  - 'go.mod'
  - 'go.sum'
area/docs:
  - 'README.md'
area/testing:
  - '**/*_test.go'
  - '**/testdata/**/*'
