area/main-binary:
- changed-files:
  - any-glob-to-any-file:
    - 'main.go'
    - 'internal/**/*'
area/sdk:
- changed-files:
  - any-glob-to-any-file:
    - 'pkg/**/*'
    - '!pkg/plugin/**/*'
area/plugin:
- changed-files:
  - any-glob-to-any-file:
    - 'pkg/plugin/**/*'
area/infra:
- changed-files:
  - any-glob-to-any-file:
    - '.github/**/*'
    - 'Makefile'
    - '.goreleaser.yml'
    - '.golangci.yml'
area/deps:
- changed-files:
  - any-glob-to-any-file:
    - 'go.mod'
    - 'go.sum'
area/docs:
- changed-files:
  - any-glob-to-any-file:
    - 'README.md'
area/testing:
- changed-files:
  - any-glob-to-any-file:
    - '**/*_test.go'
    - '**/testdata/**/*'
