# Global environment variables for builds.
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org|direct
  - VERSION_PKG=github.com/operator-framework/helm-operator-plugins/internal/version

# Hooks to run before any build is run.
before:
  hooks:
    - go version | grep --quiet "go1\.15\.6" || echo "Go binary version must be 1.15.6"
    - go mod download

# Binary builds.
builds:
  # operator-sdk build steps
  - id: helm-operator
    binary: helm-operator
    mod_timestamp: "{{ .CommitTimestamp }}"
    asmflags:
      - all=-trimpath={{ dir .Env.PWD }}
    gcflags:
      - all=-trimpath={{ dir .Env.PWD }}
    ldflags:
      - -s
      - -w
      - -X {{ .Env.VERSION_PKG }}.ScaffoldVersion={{ .Env.SCAFFOLD_VERSION }}
      - -X {{ .Env.VERSION_PKG }}.GitVersion={{ .Env.GIT_VERSION }}
      - -X {{ .Env.VERSION_PKG }}.GitCommit={{ .Env.GIT_COMMIT }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - linux_ppc64le
      - linux_s390x

# Use most recent tag and short commit for snapshot version.
snapshot:
  name_template: "{{ .Env.GIT_VERSION }}"

# We don't use archives, so skip creating them.
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: "checksums.txt"

signs:
  - signature: "${artifact}.asc"
    artifacts: checksum
    args: ["--home", ".ci/gpg/keyring", "-u", "A20B5C7E", "--output", "${signature}", "--detach-sign", "${artifact}"]
